export const ModalKey = {
    FOOD_ITEM: 'FOOD_ITEM_MODAL',
    ZIPCODE: 'ZIPCODE_MODAL',
    NEW_ORDER: 'NEW_ORDER',
    ORDER_STATUS: 'ORDER_MODAL',
    MENU: 'MENU_MODAL',
    RESET_PASSWORD: 'RESET_PASSWORD',
    ERROR_MODAL: 'ERROR_MODAL',
    REQUEST_MODAL: 'REQUEST_MODAL'
}