export const ModalKey = {
    FOOD_ITEM: 'FOOD_ITEM_MODAL',
    ZIPCODE: 'ZIPCODE_MODAL',
    PROFILE: 'PROFILE_MODAL',
    MENU: 'MENU_MODAL',
    ORDER_STATUS: 'ORDER_MODAL',
    ORDER_UPDATE: 'ORDER_UPDATE',
    RATING: 'RATING_MODAL',
}